model:
  backbone:
    config: mit_b1
    stride:
    - 4
    - 2
    - 2
    - 1
  label_feature_path: bcss_label_fea_pro_3333
  freq_proto_path: bcss_frequency_prototypes_3333
  n_ratio: 0.5
  enable_see_moe: true
  enable_ap_ce: true
  enable_dtpa: false
  enable_adaptive_dtpa: false

dataset:
  name: bcss
  train_root: data/BCSS-WSSS/train
  val_root: data/BCSS-WSSS/
  cls_num_classes: 4
  input_size:
  - 224
  - 224

work_dir:
  ckpt_dir: yxguide_freq_best_bcss_all_model
  pred_dir: yxguide_freq_best_bcss_all_model_cam
  train_log_dir: train_log

train:
  samples_per_gpu: 16
  epoch: 20
  pretrained: true
  l1: 0.3
  l2: 0.5
  l3: 1.0
  l4: 1.0
  l5: 0.3
  mask_adapter_alpha: 0.5
  merge_train: mean
  merge_test: max
  eval_iters: 2000
  warmup_iters: 2000

optimizer:
  type: AdamW
  learning_rate: 0.0002
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.0001

scheduler:
  warmup_iter: 2
  warmup_ratio: 0.1
  power: 1.0
